#!/usr/bin/env python3

import argparse

from alieneffects.theme import AlienwareTheme
from alieneffects.tui import AlienwareTUI

# argument parsing
parser = argparse.ArgumentParser()
parser.add_argument('--THEME_FILE')
args = parser.parse_args()

if args.THEME_FILE:
    theme = AlienwareTheme(args.THEME_FILE)
    theme.apply()
else:
    # default behaviour is to open TUI
    AlienwareTUI().run()
